name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-MLH-2-1-chocolatine-charlotte.weston.git"
  EXECUTABLES: "executable"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3.3.0
      - name: Check coding style
        run: check.sh $(pwd) $(pwd)

  check_program_compilation:
    needs: check_coding_style
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - name: Check repository
        uses: actions/checkout@v3.3.0
      - name: Build program
        run: make
      - name: Make clean
        run: make clean
      - name: Verify executability
        run: |
          IFS=','
          for exec in $EXECUTABLES; do
            if [ ! -x "$exec" ]; then
              exit 1
            fi
          done

  run_tests:
    runs-on: epitechcontent/epitest-docker
    needs: check_program_compilation
    timeout-minutes: 2
    steps:
      - name: Check repository
        uses: actions/checkout@v3.3.0
      - name: Run tests
        run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    needs: run_tests
    if: github.event_name == 'push'
    steps:
      - name: Runs mirror
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Mirroring action
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          repository: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
