name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-MLH-2-1-chocolatine-charlotte.weston.git"
  EXECUTABLES: "a.out"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    if: ${{ github.repository != 'git@github.com:EpitechPromo2028/B-DOP-200-MLH-2-1-chocolatine-charlotte.weston.git' }}
    steps:
      - name: Check repository
        uses: actions/checkout@v4
      - name: Check coding style
        run: check.sh $(pwd) $(pwd)
      - name: Print coding style errors
        run: |
          while IFS=':' read -r filename line type error_code; do
            echo "::error file=${filename},line=${line},title=${type} coding style error::${error_code}"
          done < coding-style-reports.log
          if [ -s coding-style-reports.log ]; then
            exit 1
          fi

  check_program_compilation:
    needs: check_coding_style
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
      - name: Check repository
        uses: actions/checkout@v4
      - name: Build program
        run: make
        timeout-minutes: 2
      - name: Make clean
        run: make clean
      - name: Verify executability
        run: |
          for exec in ${{ env.EXECUTABLES }}; do
            if [ ! -x "$exec" ]; then
              exit 1
            fi
          done

  run_tests:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - name: Check repository
        uses: actions/checkout@v4
      - name: Run tests
        run: make tests_run

  push_to_mirror:
    needs: run_tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Runs mirror
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirroring action
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
